version: '3.7'

services:
  postgres:
    image: postgres:latest
    hostname: eg_postgres
    container_name: eg_postgres
    restart: always
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=RTWZB4Nkju4gByNJrkNwrWA6MdeQ6LTk
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image:  minio/minio:latest
    hostname: eg-minio
    container_name: eg_minio
    restart: always
    depends_on:
      - postgres
    command: server --console-address :9001 /data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: tAKO6fHj1v4AwbAn4NDDSujnQoclnTs0D1Ansm
    ports:
      - "1560:9000"
      - "1561:9001"
    volumes:
     - minio_data:/data

volumes:
  minio_data:
  postgres_data:
